### PR TITLE
Plug security holes - Fixes #10 Fixes #11 Fixes #14

### LINKED ISSUE #10: Bypass 001: IE10 using 1..constructor.constructor
https://tinyurl.com/evel-bypass-01

I think this is somewhere between sandbox- and browser-bug. Technically, a fresh window should not be available in this scope.

### LINKED ISSUE #11: Bypass 002: `Function("return this")()` d'oh!
Welp, this one is too easy:
http://natevw.github.io/evel/challenge.html#Function(%22return%20this%22)()

Credit: https://twitter.com/wisecwisec/status/357861675782770689

Need to dive into the spec and figure out why `Function` breaks out of strict mode while `eval` doesn't — this could be intentional and if so we're ± hosed? We could pass in `evel.Function` as `Function`, but I suspect it's trivial to get the original back via primitives and any other exposed methods.

### LINKED ISSUE #14: Bypass 003: Recursive eval
Heh, hunting these down sure is fun.

``` javascript
eval('this')
//=> undefined
eval('eval')('this')
//=> [object Window]
```

http://natevw.github.io/evel/challenge.html#eval('eval')('this')

### PR DESCRIPTION
**Pull request by kumavis**

### CODE REVIEW

**Comment by kumavis** [comment]
informal test suite:

``` javascript
test('this',window)
test('1..constructor.constructor',Function)
test('"".constructor.constructor',Function)
test('[].slice.constructor',Function)
test('[].shift.constructor',Function)
test('Function.constructor',Function)
test('Function.prototype.constructor',Function)
test('eval',eval)
test('eval("eval")',eval)


function test(code,failCase) {
  console.log('-----------',code)
  evelOutput = evel(code)
  console.log((evelOutput+'') === (failCase+'') ? 'fail' : 'pass' )
}
```

**Comment by kumavis** [comment]
After many hours poking at this from all angles, it finally works. :triumph:
:neckbeard: I feel like I learned a lot about Javascript today.
This solution is much easier and less hacky than modifying the user's source.
Some brute force hacking took place to solve the `Function.constructor.prototype.constructor` bit, I can't say I really understand _how_ it works.
Next step: find more security holes :smiling_imp:

**Comment by kumavis** [comment]
I tried to get rid of it but it is indeed necessary. Try it out against the test suite.

**Comment by natevw** [comment]
…fascinating. Ship it!

**Comment by kumavis** [comment]
note that _before_ those global-modifying overrides

``` javascript
var normalWindow = window, iframeWindow = _gObj
evel.Function.constructor === normalWindow.Function
&&
normalWindow.Function !== iframeWindow.Function
```

**Pull request merged**
